// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  docs: [
    'intro',
    {
      type: 'category',
      label: 'Guides',
      collapsed: false,
      items: [
        'guides/getting-started',
        'guides/windows-and-drawing',
        'guides/events',
        'guides/extensions',
        'guides/custom-transports',
      ],
    },
    {
      type: 'category',
      label: 'API reference',
      collapsed: false,
      // reference/ is generated at build time by scripts/sync-docs.mjs from
      // the repo's docs/ directory; let Docusaurus pick up whatever is there.
      items: [{ type: 'autogenerated', dirName: 'reference' }],
    },
  ],
};

module.exports = sidebars;
